const POSTS = [
  {
    title: "Blog Post One",
    date: "06/23/19",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Iaculis nunc sed augue lacus viverra vitae congue eu. Porta lorem mollis aliquam ut porttitor leo a. Sed viverra tellus in hac. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Neque convallis a cras semper auctor neque. Eros donec ac odio tempor. Purus in massa tempor nec feugiat nisl pretium fusce id. Varius morbi enim nunc faucibus a pellentesque sit. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Blandit massa enim nec dui nunc mattis. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Bibendum arcu vitae elementum curabitur vitae nunc. Mi quis hendrerit dolor magna eget. Auctor urna nunc id cursus metus. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Tristique senectus et netus et malesuada fames ac turpis egestas. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eros in cursus turpis massa tincidunt. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Porttitor eget dolor morbi non arcu risus quis varius. Lorem ipsum dolor sit amet. Convallis a cras semper auctor neque vitae tempus. Dolor magna eget est lorem ipsum dolor sit amet. Ante metus dictum at tempor commodo. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Neque viverra justo nec ultrices. Ut ornare lectus sit amet est placerat in. Orci nulla pellentesque dignissim enim sit amet venenatis. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Lacus sed viverra tellus in hac habitasse. Enim facilisis gravida neque convallis a cras. Nunc faucibus a pellentesque sit. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Vel orci porta non pulvinar neque laoreet. Est placerat in egestas erat imperdiet sed euismod nisi porta. Lobortis mattis aliquam faucibus purus in massa tempor. Tellus mauris a diam maecenas sed. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Vitae justo eget magna fermentum iaculis eu. Id volutpat lacus laoreet non curabitur gravida arcu. Dignissim cras tincidunt lobortis feugiat. Amet venenatis urna cursus eget nunc scelerisque."
  },
  {
    title: "Blog Post Two",
    date: "06/30/19",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Iaculis nunc sed augue lacus viverra vitae congue eu. Porta lorem mollis aliquam ut porttitor leo a. Sed viverra tellus in hac. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Neque convallis a cras semper auctor neque. Eros donec ac odio tempor. Purus in massa tempor nec feugiat nisl pretium fusce id. Varius morbi enim nunc faucibus a pellentesque sit. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Blandit massa enim nec dui nunc mattis. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Bibendum arcu vitae elementum curabitur vitae nunc. Mi quis hendrerit dolor magna eget. Auctor urna nunc id cursus metus. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Tristique senectus et netus et malesuada fames ac turpis egestas. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eros in cursus turpis massa tincidunt. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Porttitor eget dolor morbi non arcu risus quis varius. Lorem ipsum dolor sit amet. Convallis a cras semper auctor neque vitae tempus. Dolor magna eget est lorem ipsum dolor sit amet. Ante metus dictum at tempor commodo. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Neque viverra justo nec ultrices. Ut ornare lectus sit amet est placerat in. Orci nulla pellentesque dignissim enim sit amet venenatis. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Lacus sed viverra tellus in hac habitasse. Enim facilisis gravida neque convallis a cras. Nunc faucibus a pellentesque sit. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Vel orci porta non pulvinar neque laoreet. Est placerat in egestas erat imperdiet sed euismod nisi porta. Lobortis mattis aliquam faucibus purus in massa tempor. Tellus mauris a diam maecenas sed. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Vitae justo eget magna fermentum iaculis eu. Id volutpat lacus laoreet non curabitur gravida arcu. Dignissim cras tincidunt lobortis feugiat. Amet venenatis urna cursus eget nunc scelerisque."
  },
  {
    title: "Blog Post Three",
    date: "07/07/19",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Iaculis nunc sed augue lacus viverra vitae congue eu. Porta lorem mollis aliquam ut porttitor leo a. Sed viverra tellus in hac. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Neque convallis a cras semper auctor neque. Eros donec ac odio tempor. Purus in massa tempor nec feugiat nisl pretium fusce id. Varius morbi enim nunc faucibus a pellentesque sit. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Blandit massa enim nec dui nunc mattis. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Bibendum arcu vitae elementum curabitur vitae nunc. Mi quis hendrerit dolor magna eget. Auctor urna nunc id cursus metus. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Tristique senectus et netus et malesuada fames ac turpis egestas. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eros in cursus turpis massa tincidunt. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Porttitor eget dolor morbi non arcu risus quis varius. Lorem ipsum dolor sit amet. Convallis a cras semper auctor neque vitae tempus. Dolor magna eget est lorem ipsum dolor sit amet. Ante metus dictum at tempor commodo. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Neque viverra justo nec ultrices. Ut ornare lectus sit amet est placerat in. Orci nulla pellentesque dignissim enim sit amet venenatis. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Lacus sed viverra tellus in hac habitasse. Enim facilisis gravida neque convallis a cras. Nunc faucibus a pellentesque sit. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Vel orci porta non pulvinar neque laoreet. Est placerat in egestas erat imperdiet sed euismod nisi porta. Lobortis mattis aliquam faucibus purus in massa tempor. Tellus mauris a diam maecenas sed. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Vitae justo eget magna fermentum iaculis eu. Id volutpat lacus laoreet non curabitur gravida arcu. Dignissim cras tincidunt lobortis feugiat. Amet venenatis urna cursus eget nunc scelerisque."
  }
]

export default POSTS;
